# Generated by Django 4.2.6 on 2023-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("productname", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("productImage", models.ImageField(upload_to="products/")),
                ("tags", models.CharField(max_length=255)),
            ],
        ),
    ]
